<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>report – Causal Inference Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Causal Inference Report
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Causal Inference Report</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../writing/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Airline Loyalty Causal Inference</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="airline-loyalty-causal-inference" class="level1">
<h1>Airline Loyalty Causal Inference</h1>
<section id="milestone-1-project-idea" class="level2">
<h2 class="anchored" data-anchor-id="milestone-1-project-idea">Milestone 1: Project Idea</h2>
<p>I’m really passionate about anything related to airlines, so for this project, I want to take a causal approach to analyzing airline data. Specifically, I’m interested in whether loyalty card programs actually increase an airline’s revenue, measured by Customer Lifetime Value (CLV).</p>
</section>
<section id="milestone-2-data-story" class="level2">
<h2 class="anchored" data-anchor-id="milestone-2-data-story">Milestone 2: Data Story</h2>
<p><strong>Causal Inference Question:</strong> Does having a higher loyalty card status (Star &gt; Nova &gt; Aurora) cause an increase in CLV?</p>
<p><strong>Context:</strong> I want to study if having a higher loyalty card status for an airline causes an increase in CLV. CLV is Customer Lifetime Value. It is computed as the sum of all revenues (or invoices) generated by the customer for their flight bookings over their entire membership period. Basically, it’s how much total revenue a specific customer is expected to generate. The Star loyalty card is the highest, Nova is the next highest, and Aurora is third highest. In the data, only these 3 loyalties are listed.</p>
<p>The outcome would be positive and continuous values because it’s how much revenue is expected to be made under the CLV. Predictor variables that could influence CLV is salary, education level, marital status, total flights, and enrollment year/month. Other variables that could influence our outcome could be country of residence, gender, distance traveled, points redeemed, and dollar cost of points redeemed.</p>
<p>My story is that I believe that having a loyalty card increases the revenue you will make for the airline.</p>
<p>https://www.kaggle.com/datasets/agungpambudi/airline-loyalty-campaign-program-impact-on-flights/data</p>
</section>
<section id="milestone-3-dag" class="level2">
<h2 class="anchored" data-anchor-id="milestone-3-dag">Milestone 3: DAG</h2>
<p>For the first DAG I created, I chose to use the variables from my dataset. I believed that demographics each influenced both CLV and loyalty card status. I also believed that loyalty card status affected flights and points which in turn affected CLV.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Old_DAG.png" class="img-fluid figure-img"></p>
<figcaption>Initial Old DAG</figcaption>
</figure>
</div>
<p>This is the second DAG I created when I considered even more variables than my previous DAG. I added more demographics, flight aspects, and points/economic aspects.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Old_DAG_Updated.png" class="img-fluid figure-img"></p>
<figcaption>Second Iteration of Initial Old DAG</figcaption>
</figure>
</div>
<p>I updated my DAG throughout the project and finalized it using Dagitty to give it a more polished and professional appearance. In this final DAG, the primary relationship I’m interested in is the effect of <strong>loyalty card status</strong> on <strong>Customer Lifetime Value (CLV)</strong>.</p>
<p>Several other variables influence this relationship. <strong>Travel frequency</strong> plays a key role—it affects loyalty card status because people who travel more frequently are more likely to seek the benefits that come with being a frequent flyer. It also influences total <strong>flight distance</strong>, since more trips naturally lead to a greater accumulated distance. In turn, total flight distance affects CLV, as longer flights tend to be more expensive and generate more revenue for the airline.</p>
<p><strong>Income</strong> is another upstream variable that influences travel frequency (higher income typically enables more travel), loyalty card status (some tiers may come with fees or require higher spending), and influences CLV (wealthier customers may spend more with the airline overall).</p>
<p><strong>Company marketing strategy</strong> also feeds into the system by affecting travel frequency (e.g., through increased exposure to promotions), customer engagement, and loyalty card status (via targeted advertising). All of these, in turn, impact CLV. <strong>Customer engagement</strong> directly affects both loyalty card status and CLV, as more engaged customers are more likely to enroll in loyalty programs and continue spending.</p>
<p>Finally, loyalty card status also affects <strong>upgrades/perks</strong> and <strong>length of enrollment</strong>, both of which can enhance a customer’s experience and increase their overall value to the airline, thereby contributing to CLV.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DagittyDAG.png" class="img-fluid figure-img"></p>
<figcaption>DAG</figcaption>
</figure>
</div>
</section>
<section id="milestone-4-identification-strategy" class="level2">
<h2 class="anchored" data-anchor-id="milestone-4-identification-strategy">Milestone 4: Identification Strategy</h2>
<p>Based on the DAG, here are all possible paths (23 paths) from LCS (Loyalty Card Status) to CLV (Customer Lifetime Value). For simplicity, initials are used instead of the full names from the DAG. Key: CLV is Customer Lifetime Value, LCS is Loyalty Card Status, I is Income, TF is Travel Frequency, FD is Flight Distance, CMS is Customer Marketing Strategy, and CE is Customer Engagement.</p>
<ul>
<li>LCS, CLV</li>
<li>LCS, I, CLV</li>
<li>LCS, I, TF, CLV</li>
<li>LCS, I, TF, FD, CLV</li>
<li>LCS, I, TF, CMS, CLV</li>
<li>LCS, I, TF, CMS, CE, CLV</li>
<li>LCS, TF, CLV</li>
<li>LCS, TF, I, CLV</li>
<li>LCS, TF, FD, CLV</li>
<li>LSC, TF, CMS, CLV</li>
<li>LCS, TF, CMS, CE, CLV</li>
<li>LCS, CMS, CLV</li>
<li>LCS, CMS, CE, CLV</li>
<li>LCS, CMS, TF, CLV</li>
<li>LCS, CMS, TF, FD, CLV</li>
<li>LCS, CMS, TF, I, CLV</li>
<li>LCS, CE, CLV</li>
<li>LCS, CE, CMS, CLV</li>
<li>LCS, CE, CMS, TF, CLV</li>
<li>LCS, CE, CMS, TF, FD, CLV</li>
<li>LCS, CE, CMS, TF, I, CLV</li>
<li>LCS, UP, CLV</li>
<li>LCS, LTE, CLV</li>
</ul>
<p>Direct pipes - can estimate total causal effect through them</p>
<ul>
<li>LCS, UP, CLV</li>
<li>LCS, LTE, CLV</li>
</ul>
<p>Here are the backdoors &amp; what to do about them:</p>
<ul>
<li>LCS, I, CLV – Fork, Condition on I</li>
<li>LCS, I, TF, CLV – Fork, Pipe, Condition on TF</li>
<li>LCS, I, TF, FD, CLV – Fork, Pipe, Pipe, Condition on FD</li>
<li>LCS, I, TF, CMS, CLV –Fork, Collider, Fork, Condition on CMS</li>
<li>LCS, I, TF, CMS, CE, CLV – Fork, Collider, Fork, Pipe, Condition on CE</li>
<li>LCS, TF, CLV – Fork, Condition on TF</li>
<li>LCS, TF, I, CLV – Fork, Pipe, Condition on I</li>
<li>LCS, TF, FD, CLV – Fork, Pipe, Condition on FD</li>
<li>LSC, TF, CMS, CLV – Pipe, Fork, Condition on CMS</li>
<li>LCS, TF, CMS, CE, CLV – Pipe, Fork, Pipe, Condition on CE</li>
<li>LCS, CMS, CLV – Fork, Condition on CMS</li>
<li>LCS, CMS, CE, CLV – Fork, Pipe, Condition on CE</li>
<li>LCS, CMS, TF, CLV – Fork, Pipe, Condition on CMS</li>
<li>LCS, CMS, TF, FD, CLV – Fork, Pipe, Pipe, Condition on CMS &amp; TF</li>
<li>LCS, CMS, TF, I, CLV – Fork, Collider, Fork, Condition on CMS, TF, &amp; I</li>
<li>LCS, CE, CLV – Fork, Condition on CE</li>
<li>LCS, CE, CMS, CLV – Pipe, Fork, Condition on CE or CMS</li>
<li>LCS, CE, CMS, TF, CLV – Pipe, Fork, Pipe, Condition on CE or CMS or TF</li>
<li>LCS, CE, CMS, TF, FD, CLV – Pipe, Fork, Pipe, Pipe, Condition on CE or CMS or TF</li>
<li>LCS, CE, CMS, TF, I, CLV – Pipe, Fork, Collider, Fork, Condition on CE or CMS or TF or I</li>
</ul>
<p>Adjustment Set: I, TF, CMS, and CE. In order to do causal inference, I need to condition on income, travel frequency, customer marketing strategy, and customer engagement.</p>
</section>
<section id="milestone-5-simulate-data-and-recover-parameters" class="level2">
<h2 class="anchored" data-anchor-id="milestone-5-simulate-data-and-recover-parameters">Milestone 5: Simulate Data and Recover Parameters</h2>
<p>In this code, a simulated dataset is created using various predictors (independent variables) to estimate the Customer Lifetime Value (CLV), which is the outcome (dependent variable). The code first defines the parameter values for each predictor, including factors like income, flight distance, travel frequency, customer marketing strategy, customer engagement, and loyalty card status. It then generates random values for these predictors and combines them in a linear equation to simulate CLV. This equation also includes a small amount of random noise to make the data more realistic.</p>
<p>After generating the data, a linear regression model is applied to it using the <code>LinearRegression</code> function from the <code>sklearn</code> library. The model is trained using the predictors (<code>X</code>) and the simulated CLV values. Once the model is trained, the code prints the estimated coefficients for each predictor, which represent how each variable impacts the CLV. By examining these coefficients, we can understand the relationship between the predictors and CLV.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seed for reproducibility</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the parameter values.</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>beta0 <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>income <span class="op">=</span> <span class="dv">70000</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>flight_dist <span class="op">=</span> <span class="dv">3500</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>travel_freq <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>cust_marketing_strat <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>cust_engagement <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>loyalty_card_status <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>sim_data <span class="op">=</span> (</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Simulate predictors using appropriate np.random distributions.</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    pl.DataFrame({</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>        <span class="st">'x'</span>: np.random.uniform(<span class="dv">0</span>, <span class="dv">7</span>, size<span class="op">=</span>n),</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">'flight_dist'</span>: np.random.uniform(<span class="dv">0</span>, <span class="dv">10000</span>, size<span class="op">=</span>n),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">'travel_freq'</span>: np.random.uniform(<span class="dv">1</span>, <span class="dv">10</span>, size<span class="op">=</span>n),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">'cust_marketing_strat'</span>: np.random.uniform(<span class="dv">0</span>, <span class="dv">5</span>, size<span class="op">=</span>n),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">'cust_engagement'</span>: np.random.uniform(<span class="dv">1</span>, <span class="dv">10</span>, size<span class="op">=</span>n),</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">'loyalty_card_status'</span>: np.random.choice([<span class="dv">0</span>, <span class="dv">1</span>], size<span class="op">=</span>n)  <span class="co"># New binary predictor</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Use predictors and parameter values to simulate the outcome.</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    .with_columns([ </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>        (</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>            beta0 <span class="op">+</span> income <span class="op">*</span> pl.col(<span class="st">'x'</span>) <span class="op">+</span> flight_dist <span class="op">*</span> pl.col(<span class="st">'flight_dist'</span>) <span class="op">+</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>            travel_freq <span class="op">*</span> pl.col(<span class="st">'travel_freq'</span>) <span class="op">+</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>            cust_marketing_strat <span class="op">*</span> pl.col(<span class="st">'cust_marketing_strat'</span>) <span class="op">+</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>            cust_engagement <span class="op">*</span> pl.col(<span class="st">'cust_engagement'</span>) <span class="op">+</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>            loyalty_card_status <span class="op">*</span> pl.col(<span class="st">'loyalty_card_status'</span>) <span class="op">+</span>  <span class="co"># Adding loyalty_card_status with a coefficient (e.g., 1000)</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>            np.random.normal(<span class="dv">0</span>, <span class="dv">3</span>, size<span class="op">=</span>n)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>        ).alias(<span class="st">'CLV'</span>)  <span class="co"># Renaming y to CLV</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the data</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>sim_data</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the data</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co"># sns.scatterplot(data=sim_data, x='x', y='CLV')</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="co"># sns.lmplot(data=sim_data, x='x', y='CLV', height=6, aspect=1, scatter_kws={'s': 10}, line_kws={'color': 'red'})</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the X matrix and CLV vector.</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sim_data[[<span class="st">'x'</span>, <span class="st">'flight_dist'</span>, <span class="st">'travel_freq'</span>, <span class="st">'cust_marketing_strat'</span>, <span class="st">'cust_engagement'</span>, <span class="st">'loyalty_card_status'</span>]]</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>CLV <span class="op">=</span> sim_data[<span class="st">'CLV'</span>]</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a linear regression model.</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression(fit_intercept<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the model.</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>model.fit(X, CLV)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the coefficients</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Intercept: </span><span class="sc">{</span>model<span class="sc">.</span>intercept_<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope for x: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope for flight_dist: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope for travel_freq: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope for cust_marketing_strat: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">3</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope for cust_engagement: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">4</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope for loyalty_card_status: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">5</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="co"># Have you recovered the parameters?</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="co"># Yes</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Intercept: 1001.5413256846368</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for x: 69999.86275851386</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for flight_dist: 3499.9999835407984</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for travel_freq: 5.112035246336143</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for cust_marketing_strat: 0.8774017286699657</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for cust_engagement: 2.7190101859602787</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for loyalty_card_status: 1000.1457705767122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The code worked well because we successfully recovered our parameters and our estimated slopes are incredibly accurate to the parameter values we set.</p>
</section>
<section id="milestone-6-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="milestone-6-exploratory-data-analysis">Milestone 6: Exploratory Data Analysis</h2>
<p><strong>Loyalty Card Status:</strong> Loyalty Card Status is which airline loyalty card you have, whether that’s Star, Nova, or Aurora. Here is a break down of the data by type of loyalty card. We can see that most people have the highest loyalty card, Star, followed by Nova and then by Aurora.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot for loyalty_card_status</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> sns.countplot(x<span class="op">=</span><span class="st">'Loyalty Card'</span>, data<span class="op">=</span>data)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set labels and title</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loyalty Card Status'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Loyalty Card Status'</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the count labels on top of the bars without decimals</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> ax.patches:</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="ss">f'</span><span class="sc">{</span><span class="bu">int</span>(p.get_height())<span class="sc">}</span><span class="ss">'</span>, </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>                (p.get_x() <span class="op">+</span> p.get_width() <span class="op">/</span> <span class="fl">2.</span>, p.get_height()), </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>                ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'center'</span>, </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>                fontsize<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">'black'</span>, </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>                xytext<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">5</span>), textcoords<span class="op">=</span><span class="st">'offset points'</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the figure</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'loyalty_card_distribution_bar_chart.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="loyalty_card_distribution_bar_chart.png" class="img-fluid figure-img"></p>
<figcaption>Loyalty Card Status Bar Chart</figcaption>
</figure>
</div>
<p><strong>Income:</strong> Most people have an income between roughly $80,000 and $125,000, which makes sense. There are of course some who have higher salaries, hence the right skew.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the data by removing null, empty, and negative salary values</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_clean <span class="op">=</span> data[data[<span class="st">'Salary'</span>].notnull() <span class="op">&amp;</span> (data[<span class="st">'Salary'</span>] <span class="op">!=</span> <span class="st">''</span>)]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>data_clean <span class="op">=</span> data_clean[data_clean[<span class="st">'Salary'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the histogram</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>plt.hist(data_clean[<span class="st">'Salary'</span>], bins<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span><span class="st">'skyblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Salary'</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Salary'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the figure</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/salary_histogram.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hist_of_salary.png" class="img-fluid figure-img"></p>
<figcaption>Salary Histogram</figcaption>
</figure>
</div>
<p><strong>Travel Frequency:</strong> This is how frequently a person travels. I do not have this variable in my dataset.</p>
<p><strong>Customer Marketing Strategy:</strong> This is how well the airline markets their products. I don’t have a direct variable for this in my dataset but I do know which enrollment type people did when they got a loyalty card as well as which loyalty card.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot for Enrollment Type</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> sns.countplot(x<span class="op">=</span><span class="st">'Enrollment Type'</span>, data<span class="op">=</span>data)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set labels and title</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Enrollment Type'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Enrollment Type'</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the count labels on top of the bars without decimals</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> ax.patches:</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="ss">f'</span><span class="sc">{</span><span class="bu">int</span>(p.get_height())<span class="sc">}</span><span class="ss">'</span>, </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>                (p.get_x() <span class="op">+</span> p.get_width() <span class="op">/</span> <span class="fl">2.</span>, p.get_height()), </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>                ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'center'</span>, </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>                fontsize<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">'black'</span>, </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>                xytext<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">5</span>), textcoords<span class="op">=</span><span class="st">'offset points'</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the figure</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/enrollment_type_bar_chart.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="enrollment_type_bar_chart.png" class="img-fluid figure-img"></p>
<figcaption>Enrollment Type Bar Chart</figcaption>
</figure>
</div>
<p><strong>Customer Engagement:</strong> This is how involved a person is with the airline. I do not have this variable in my dataset.</p>
<p><strong>CLV:</strong> Customer Lifetime Value is how much revenue a single person generates the airline company. It seems that most people earn the airline between roughly $2,000 and $15,000.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the data and remove negative values</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>data_clean <span class="op">=</span> data[data[<span class="st">'CLV'</span>].notnull() <span class="op">&amp;</span> (data[<span class="st">'CLV'</span>] <span class="op">!=</span> <span class="st">''</span>)]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>data_clean <span class="op">=</span> data_clean[data_clean[<span class="st">'CLV'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]  </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the histogram</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.hist(data_clean[<span class="st">'CLV'</span>], bins<span class="op">=</span><span class="dv">6</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add titles and labels</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Customer Lifetime Value (CLV)'</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Customer Lifetime Value (CLV)'</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the figure</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/clv_histogram.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hist_clv.png" class="img-fluid figure-img"></p>
<figcaption>CLV Histogram</figcaption>
</figure>
</div>
</section>
<section id="milestone-7-estimate-causal-effects" class="level2">
<h2 class="anchored" data-anchor-id="milestone-7-estimate-causal-effects">Milestone 7: Estimate Causal Effects</h2>
<p>In this milestone, we estimate the causal effects of several customer-related factors on Customer Lifetime Value (CLV) using a Bayesian linear regression approach. We start by simulating a dataset with realistic variability in customer behavior, including features such as flight distance, travel frequency, marketing strategy engagement, and loyalty card status. We then specify a probabilistic model using PyMC, assigning priors to the intercept and coefficients, and defining a likelihood function based on the simulated CLV data. After sampling from the posterior distribution, we summarize the results and visualize the marginal posterior distributions to assess parameter uncertainty and convergence. This modeling approach allows for more nuanced inference compared to traditional frequentist methods, particularly when quantifying uncertainty around effect estimates.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># eval: false</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> arviz <span class="im">as</span> az</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the parameter values.</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>beta0 <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>income <span class="op">=</span> <span class="dv">70000</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>flight_dist <span class="op">=</span> <span class="dv">3500</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>travel_freq <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>cust_marketing_strat <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>cust_engagement <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>loyalty_card_status <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate Data</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>sim_data <span class="op">=</span> (</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    pl.DataFrame({</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">'x'</span>: np.random.uniform(<span class="dv">0</span>, <span class="dv">7</span>, size<span class="op">=</span>n),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">'flight_dist'</span>: np.random.uniform(<span class="dv">0</span>, <span class="dv">10000</span>, size<span class="op">=</span>n),</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">'travel_freq'</span>: np.random.uniform(<span class="dv">1</span>, <span class="dv">10</span>, size<span class="op">=</span>n),</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">'cust_marketing_strat'</span>: np.random.uniform(<span class="dv">0</span>, <span class="dv">5</span>, size<span class="op">=</span>n),</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">'cust_engagement'</span>: np.random.uniform(<span class="dv">1</span>, <span class="dv">10</span>, size<span class="op">=</span>n),</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">'loyalty_card_status'</span>: np.random.choice([<span class="dv">0</span>, <span class="dv">1</span>], size<span class="op">=</span>n)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    .with_columns([ </span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>        (</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>            beta0 <span class="op">+</span> income <span class="op">*</span> pl.col(<span class="st">'x'</span>) <span class="op">+</span> flight_dist <span class="op">*</span> pl.col(<span class="st">'flight_dist'</span>) <span class="op">+</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>            travel_freq <span class="op">*</span> pl.col(<span class="st">'travel_freq'</span>) <span class="op">+</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>            cust_marketing_strat <span class="op">*</span> pl.col(<span class="st">'cust_marketing_strat'</span>) <span class="op">+</span></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>            cust_engagement <span class="op">*</span> pl.col(<span class="st">'cust_engagement'</span>) <span class="op">+</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>            loyalty_card_status <span class="op">*</span> pl.col(<span class="st">'loyalty_card_status'</span>) <span class="op">+</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>            np.random.normal(<span class="dv">0</span>, <span class="dv">3</span>, size<span class="op">=</span>n)</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>        ).alias(<span class="st">'CLV'</span>)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate predictors and outcome</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sim_data[[<span class="st">'x'</span>, <span class="st">'flight_dist'</span>, <span class="st">'travel_freq'</span>, <span class="st">'cust_marketing_strat'</span>, <span class="st">'cust_engagement'</span>, <span class="st">'loyalty_card_status'</span>]].to_numpy()</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>CLV <span class="op">=</span> sim_data[<span class="st">'CLV'</span>].to_numpy()</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Bayesian Linear Regression Model</span></span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> clv_model:</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Priors</span></span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>    alpha <span class="op">=</span> pm.Normal(<span class="st">'alpha'</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> pm.Normal(<span class="st">'beta'</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">50000</span>, shape<span class="op">=</span>X.shape[<span class="dv">1</span>])  <span class="co"># One coefficient per feature</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> pm.HalfNormal(<span class="st">'sigma'</span>, sigma<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Likelihood</span></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> alpha <span class="op">+</span> X <span class="op">@</span> beta  <span class="co"># Matrix multiplication of predictors and coefficients</span></span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>    y_obs <span class="op">=</span> pm.Normal(<span class="st">'y_obs'</span>, mu<span class="op">=</span>mu, sigma<span class="op">=</span>sigma, observed<span class="op">=</span>CLV)</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Posterior Sampling</span></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>    trace <span class="op">=</span> pm.sample(<span class="dv">1000</span>, return_inferencedata<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of results</span></span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> az.summary(trace, round_to<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(summary)</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the figure as a file</span></span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"../figures/trace_plot.png"</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">"tight"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [alpha, beta, sigma]</code></pre>
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace">C:\Users\rhigb\anaconda3\envs\pymc_env\lib\site-packages\rich\live.py:231: UserWarning: install "ipywidgets" for 
Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')
</pre>
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"></pre>
<pre><code>Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 46 seconds.

             mean    sd    hdi_3%   hdi_97%  mcse_mean  mcse_sd  ess_bulk  \
alpha     1001.54  1.57    998.56   1004.44       0.04     0.03   1716.47   
beta[0]  69999.86  0.16  69999.55  70000.15       0.00     0.00   2980.24   
beta[1]   3500.00  0.00   3500.00   3500.00       0.00     0.00   2676.18   
beta[2]      5.11  0.13      4.87      5.34       0.00     0.00   2797.21   
beta[3]      0.88  0.23      0.46      1.33       0.00     0.00   2803.72   
beta[4]      2.72  0.11      2.51      2.95       0.00     0.00   2857.42   
beta[5]   1000.14  0.66    998.90   1001.36       0.01     0.01   2888.85   
sigma        3.14  0.23      2.73      3.58       0.00     0.00   3357.19   

         ess_tail  r_hat  
alpha     2254.65    1.0  
beta[0]   2647.25    1.0  
beta[1]   2493.25    1.0  
beta[2]   3006.42    1.0  
beta[3]   2695.00    1.0  
beta[4]   2503.09    1.0  
beta[5]   2612.51    1.0  
sigma     2569.07    1.0  

&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="trace_plot.png" class="img-fluid figure-img"></p>
<figcaption>trace plot</figcaption>
</figure>
</div>
<p>The posterior summary shows that the model recovered the true parameter values with high accuracy and precision. All estimated coefficients are very close to the values used in the data-generating process. For instance, beta[0] (the coefficient on x) is estimated at 69,999.86, nearly identical to the true value of 70,000, and beta[1] for flight_dist is exactly 3500.00, with virtually no variation. The same holds for beta[5] (loyalty_card_status), which was set to 1000 and estimated at 1000.14.</p>
<p>The standard deviations and HDIs (highest density intervals) around these estimates are quite narrow, suggesting low uncertainty and strong signal in the data. The noise parameter sigma is estimated at 3.14, closely matching the standard deviation of the noise added during simulation. Additionally, convergence diagnostics are excellent—<span class="math inline">\(\hat{R}\)</span> values are all 1.0, and effective sample sizes (ESS) are comfortably high, indicating stable and reliable inference across chains.</p>
<p>From a causal perspective, these results are encouraging. The fact that the posterior means align closely with the known data-generating values suggests that the model can reliably recover true causal effects when the assumptions are met.</p>
</section>
<section id="milestone-8-intermediate-presentation" class="level2">
<h2 class="anchored" data-anchor-id="milestone-8-intermediate-presentation">Milestone 8: Intermediate Presentation</h2>
<p>See my intermediate presentation <a href="https://github.com/RebeccaHull/causal_inference/blob/milestone-15/presentations/Intermediate_CI_Presentation_Hull.qmd">Intermediate Presentation Slides</a>. To summarize some feedback:</p>
<ul>
<li>I need to make sure my salary histogram does not have a bin nor data that goes below 0.</li>
<li>I need to make sure that my CLV histogram has touching bars. Additionally, I need to set the number of bins to something that makes sense for the data (so in my case, more bins).</li>
</ul>
</section>
<section id="milestone-9-run-conjoint-experiment" class="level2">
<h2 class="anchored" data-anchor-id="milestone-9-run-conjoint-experiment">Milestone 9: Run Conjoint Experiment</h2>
<p>I ran a conjoint experiment through a survey using Discover Sawtooth Software. I was testing how desirable different package deals (with specified benefits) were for different loyalty cards. I got 33 responses. Here are my results:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Ever been on a plane_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>Been on airplane?</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Employed rn_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>Are you employed?</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - 18_plus_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>Are you 18+?</figcaption>
</figure>
</div>
<p>If anyone answered “no” to these first 3 questions, the survey ended for them. I wanted to make sure that respondents were adults with jobs (so they have money for considering flights) and have had experience with the airline industry. 25 people continued with the survey because they answered yes to each of the 3 preliminary questions.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - How often do you fly_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>How often do you fly?</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Travel Reason_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>Why do you fly?</figcaption>
</figure>
</div>
<p>Most people travel once - a few times a year. Most people travel either to see family and friends or for vacation.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Loyalty Card Package Options - Card Type Chart.png" class="img-fluid figure-img"></p>
<figcaption>Package Names: Star, Nova, Aurora</figcaption>
</figure>
</div>
<p>Since card name was randomly assigned with benefits to create a package, there isn’t anything to glean from this chart other than maybe people like the name “Nova” more.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Loyalty Card Package Options - Benefit 1 Chart.png" class="img-fluid figure-img"></p>
<figcaption>Benefit Grouping 1</figcaption>
</figure>
</div>
<p>20% or 25% discount on flight tickets were really desired.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Loyalty Card Package Options - Benefit 2 Chart.png" class="img-fluid figure-img"></p>
<figcaption>Benefit Grouping 2</figcaption>
</figure>
</div>
<p>Free seat upgrades and exclusive deals with partner services were much more popular than lounge access.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Loyalty Card Package Options - Price Chart.png" class="img-fluid figure-img"></p>
<figcaption>Package Prices</figcaption>
</figure>
</div>
<p>The most favorable choice was the cheapest package deal per month with the least favorable being the most expensive. This makes perfect sense.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Loyalty Card Package Options - Attribute importance Chart.png" class="img-fluid figure-img"></p>
<figcaption>Attribute Importance</figcaption>
</figure>
</div>
<p>Price was most important out the the 4 attributes, followed by benefit 2 (which had lounging, boarding, seating, and exclusive deals) and then by benefit 1 (which had discounted tickets and free checked bags).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Buy a card_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>Would you buy a loyalty card?</figcaption>
</figure>
</div>
<p>24% of survey respondents would consider buying a loyalty card for themselves.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Yearly Income Chart.png" class="img-fluid figure-img"></p>
<figcaption>What’s your yearly income bracket?</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Education Level Chart.png" class="img-fluid figure-img"></p>
<figcaption>What’s your education level?</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Age Chart.png" class="img-fluid figure-img"></p>
<figcaption>What’s your age bracket?</figcaption>
</figure>
</div>
<p>The majority of survey respondents are young adults who are either still in their Bachelors degree (not finished so they may have answered “High School or GED”) or have finished and their yearly income is very low because they are either newly graduated or still in college.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Gender Chart.png" class="img-fluid figure-img"></p>
<figcaption>What’s your gender?</figcaption>
</figure>
</div>
<p>60% of respondents were female, 40% were male.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Airline Loyalty Conjoint Survey - Married_ Chart.png" class="img-fluid figure-img"></p>
<figcaption>Are you married?</figcaption>
</figure>
</div>
<p>There is nearly a 50-50% split of marital status.</p>
</section>
<section id="milestone-10-implement-diff-in-diff-strategy" class="level2">
<h2 class="anchored" data-anchor-id="milestone-10-implement-diff-in-diff-strategy">Milestone 10: Implement Diff-in-Diff Strategy</h2>
<p>The purpose of Difference-in-Differences (Diff-in-Diff) is to estimate the causal effect of a treatment or intervention by comparing the changes in outcomes over time between a treatment group and a control group. I created a synthetic dataset to use this strategy.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Packages</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> arviz <span class="im">as</span> az</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Outcomes</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> outcome(t, control_intercept, treat_intercept_delta, trend, Δ, group, treated):</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> control_intercept <span class="op">+</span> (treat_intercept_delta <span class="op">*</span> group) <span class="op">+</span> (trend <span class="op">*</span> t) <span class="op">+</span> (Δ <span class="op">*</span> treated <span class="op">*</span> group)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> is_treated(t, intervention_time, group):</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (t <span class="op">&gt;</span> intervention_time) <span class="op">*</span> group</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># True parameters</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>control_intercept <span class="op">=</span> <span class="dv">5000</span>  <span class="co"># CLV for non-members</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>baseline_treat_intercept <span class="op">=</span> <span class="dv">6000</span>  <span class="co"># CLV for Aurora before upgrade</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>trend <span class="op">=</span> <span class="dv">3000</span>  <span class="co"># General CLV increase over time</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>Δ <span class="op">=</span> <span class="dv">2000</span>  <span class="co"># Treatment effect: additional CLV boost from upgrading to Star</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>intervention_time <span class="op">=</span> <span class="fl">0.5</span>  <span class="co"># When the upgrade happens</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating Synthetic Dataset</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"group"</span>: [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>] <span class="op">*</span> <span class="dv">10</span>,  <span class="co"># 0 = No Loyalty Card, 1 = Aurora</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"t"</span>: [<span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="fl">1.0</span>] <span class="op">*</span> <span class="dv">10</span>,  <span class="co"># Time periods (Pre/Post)</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"unit"</span>: np.concatenate([[i] <span class="op">*</span> <span class="dv">2</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">20</span>)]),</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"treated"</span>] <span class="op">=</span> is_treated(df[<span class="st">"t"</span>], intervention_time, df[<span class="st">"group"</span>])</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"y"</span>] <span class="op">=</span> outcome(</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"t"</span>],</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>    control_intercept,</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    baseline_treat_intercept <span class="op">-</span> control_intercept,  <span class="co"># Initial difference in CLV</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>    trend,</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>    Δ,</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"group"</span>],</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"treated"</span>],</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"y"</span>] <span class="op">+=</span> np.random.normal(<span class="dv">0</span>, <span class="dv">500</span>, df.shape[<span class="dv">0</span>])  <span class="co"># Add noise</span></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequentist Diff-in-Diff Calculation</span></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>diff_control <span class="op">=</span> (</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>    df.loc[(df[<span class="st">"t"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">"group"</span>] <span class="op">==</span> <span class="dv">0</span>)][<span class="st">"y"</span>].mean()</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> df.loc[(df[<span class="st">"t"</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">"group"</span>] <span class="op">==</span> <span class="dv">0</span>)][<span class="st">"y"</span>].mean()</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Pre/post difference in control group = </span><span class="sc">{</span>diff_control<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>diff_treat <span class="op">=</span> (</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>    df.loc[(df[<span class="st">"t"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">"group"</span>] <span class="op">==</span> <span class="dv">1</span>)][<span class="st">"y"</span>].mean()</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> df.loc[(df[<span class="st">"t"</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">"group"</span>] <span class="op">==</span> <span class="dv">1</span>)][<span class="st">"y"</span>].mean()</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Pre/post difference in treatment group = </span><span class="sc">{</span>diff_treat<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>diff_in_diff <span class="op">=</span> diff_treat <span class="op">-</span> diff_control</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Difference in differences = </span><span class="sc">{</span>diff_in_diff<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a><span class="co"># Bayesian Approach</span></span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> model:</span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Data</span></span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>    t <span class="op">=</span> pm.MutableData(<span class="st">"t"</span>, df[<span class="st">"t"</span>].values, dims<span class="op">=</span><span class="st">"obs_idx"</span>)</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a>    treated <span class="op">=</span> pm.MutableData(<span class="st">"treated"</span>, df[<span class="st">"treated"</span>].values, dims<span class="op">=</span><span class="st">"obs_idx"</span>)</span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a>    group <span class="op">=</span> pm.MutableData(<span class="st">"group"</span>, df[<span class="st">"group"</span>].values, dims<span class="op">=</span><span class="st">"obs_idx"</span>)</span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Priors</span></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>    _control_intercept <span class="op">=</span> pm.Normal(<span class="st">"control_intercept"</span>, <span class="dv">5000</span>, <span class="dv">1000</span>)</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a>    _treat_intercept_delta <span class="op">=</span> pm.Normal(<span class="st">"treat_intercept_delta"</span>, <span class="dv">1000</span>, <span class="dv">1000</span>)</span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>    _trend <span class="op">=</span> pm.Normal(<span class="st">"trend"</span>, <span class="dv">3000</span>, <span class="dv">1000</span>)</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>    _Δ <span class="op">=</span> pm.Normal(<span class="st">"Δ"</span>, <span class="dv">2000</span>, <span class="dv">1000</span>)</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> pm.HalfNormal(<span class="st">"sigma"</span>, <span class="dv">500</span>)</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Expectation</span></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> pm.Deterministic(</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mu"</span>,</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>        outcome(t, _control_intercept, _treat_intercept_delta, _trend, _Δ, group, treated),</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>        dims<span class="op">=</span><span class="st">"obs_idx"</span>,</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Likelihood</span></span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a>    pm.Normal(<span class="st">"obs"</span>, mu, sigma, observed<span class="op">=</span>df[<span class="st">"y"</span>].values, dims<span class="op">=</span><span class="st">"obs_idx"</span>)</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> model:</span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a>    idata <span class="op">=</span> pm.sample()</span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a>az.plot_trace(idata, var_names<span class="op">=</span><span class="st">"~mu"</span>)<span class="op">;</span></span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a><span class="co"># Results</span></span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre/post difference in control group = 3006.32</span></span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre/post difference in treatment group = 4935.59</span></span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a><span class="co"># Difference in differences = 1929.27</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Those who upgraded to a higher loyalty status (aka got the treatment) had an increase of $1929.27 in CLV after they upgraded from an Aurora card to a higher status loyalty card.</p>
</section>
<section id="milestone-11-clean-up-project-report" class="level2">
<h2 class="anchored" data-anchor-id="milestone-11-clean-up-project-report">Milestone 11: Clean Up Project Report</h2>
<p>I created and cleaned up my project report in the writing folder.</p>
<p>A few changes I made:</p>
<ul>
<li><p>The CLV histogram now have bins that touch and a more appropriate number of bins.</p></li>
<li><p>The Salary histogram no longer has a bin below zero (since you can’t have a negative salary).</p></li>
</ul>
</section>
<section id="milestone-12-matching-strategy" class="level2">
<h2 class="anchored" data-anchor-id="milestone-12-matching-strategy">Milestone 12: Matching Strategy</h2>
<p>I implemented a matching strategy on the Airline Loyalty dataset using propensity scores to see if getting a higher loyalty card (Star or Nova) caused an increase in CLV. The result was surprising! Not only did it not increase CLV, it actually <strong>decreased</strong> CLV!</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Packages</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> SimpleImputer</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> NearestNeighbors</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load your data</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/CLV.csv"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Filter dataset</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only people with Aurora, Nova, or Star</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[df[<span class="st">'Loyalty Card'</span>].isin([<span class="st">'Aurora'</span>, <span class="st">'Nova'</span>, <span class="st">'Star'</span>])]</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Filter out cancellations unless they upgraded</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co"># This will require you to define what "upgraded" means and check for card progression</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># For now, let’s filter out all cancellations for simplicity</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[df[<span class="st">'Cancellation Year'</span>].isna()]</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Define treatment variable</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'treatment'</span>] <span class="op">=</span> df[<span class="st">'Loyalty Card'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="dv">1</span> <span class="cf">if</span> x <span class="kw">in</span> [<span class="st">'Nova'</span>, <span class="st">'Star'</span>] <span class="cf">else</span> <span class="dv">0</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Select covariates</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>covariates <span class="op">=</span> [<span class="st">'Country'</span>, <span class="st">'Province'</span>, <span class="st">'City'</span>, <span class="st">'Postal Code'</span>, <span class="st">'Gender'</span>, <span class="st">'Education'</span>, </span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>              <span class="st">'Marital Status'</span>, <span class="st">'Enrollment Type'</span>, <span class="st">'Enrollment Year'</span>, <span class="st">'Enrollment Month'</span>, <span class="st">'Salary'</span>]</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Handle missing salary with median imputation</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>imputer <span class="op">=</span> SimpleImputer(strategy<span class="op">=</span><span class="st">'median'</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Salary'</span>] <span class="op">=</span> imputer.fit_transform(df[[<span class="st">'Salary'</span>]])</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode categorical variables</span></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>df_encoded <span class="op">=</span> pd.get_dummies(df[covariates], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Estimate propensity scores</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>X_scaled <span class="op">=</span> scaler.fit_transform(df_encoded)</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>log_reg <span class="op">=</span> LogisticRegression(max_iter<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>log_reg.fit(X_scaled, df[<span class="st">'treatment'</span>])</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'propensity_score'</span>] <span class="op">=</span> log_reg.predict_proba(X_scaled)[:, <span class="dv">1</span>]</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Matching using Nearest Neighbors</span></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>treated <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>control <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Match each treated unit to the nearest control unit</span></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>nn <span class="op">=</span> NearestNeighbors(n_neighbors<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>nn.fit(control[[<span class="st">'propensity_score'</span>]])</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>distances, indices <span class="op">=</span> nn.kneighbors(treated[[<span class="st">'propensity_score'</span>]])</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>matched_control <span class="op">=</span> control.iloc[indices.flatten()].copy()</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>matched_treated <span class="op">=</span> treated.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Compare outcomes</span></span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>matched_df <span class="op">=</span> pd.concat([matched_treated, matched_control])</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average CLV - Treated:"</span>, matched_treated[<span class="st">'CLV'</span>].mean())</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average CLV - Matched Control:"</span>, matched_control[<span class="st">'CLV'</span>].mean())</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estimated treatment effect on CLV:"</span>, matched_treated[<span class="st">'CLV'</span>].mean() <span class="op">-</span> matched_control[<span class="st">'CLV'</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Average Treated CLV (upgrade to Nova or Star): $7,282.51</p>
<p>Average Matched Control CLV (Aurora): $10,817.40</p>
<p><strong>Estimated treatment effect on CLV: $-3,534.89</strong></p>
<p><em>Possible Reasons Behind the Results:</em></p>
<ul>
<li><p>Card upgrades may be a <strong>response to low CLV</strong>, not the cause — companies might give better cards to underperforming customers to boost engagement.</p></li>
<li><p><strong>Unobserved factors</strong> like shopping frequency could still bias results, even with matching.</p></li>
<li><p><strong>Aurora users might naturally have higher CLV</strong>, possibly because they’re long-time or high-value customers who never needed an upgrade.</p></li>
<li><p>If there are <strong>very few Aurora members</strong>, the matched control group could be small and skewed by outliers with unusually high CLV.</p></li>
</ul>
<p>From this, I believe people with higher-tier cards (Nova or Star) have <strong>lower</strong> CLV than similar people with Aurora cards. This is most likely due to a small percentage of Aurora members. Only 20.5% of the dataset customers had Aurora cards.</p>
</section>
<section id="milestone-13-regression-discontinuity-and-marginal-effects" class="level2">
<h2 class="anchored" data-anchor-id="milestone-13-regression-discontinuity-and-marginal-effects">Milestone 13: Regression Discontinuity and Marginal Effects</h2>
<p>I do not think these apply to this project. To see if regression discontinuity made sense, I graphed salary vs CLV and there is not a clear cutoff or discontinuity in the scatterplot. It was fun learning about this concept though!</p>
</section>
<section id="milestone-14-final-presentation" class="level2">
<h2 class="anchored" data-anchor-id="milestone-14-final-presentation">Milestone 14: Final Presentation</h2>
<p>I created my final presentation and presented it to the class!</p>
</section>
<section id="milestone-15-finish-report-and-github-pages" class="level2">
<h2 class="anchored" data-anchor-id="milestone-15-finish-report-and-github-pages">Milestone 15: Finish Report and GitHub Pages</h2>
<p>I finished my report and created my GitHUb page to represent my portfolio!</p>
<p>Linear Regression Results on my Dataset:</p>
<p>This code estimates the causal effect of loyalty status on CLV under the assumption that your adjustment set blocks all backdoor paths.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Libraries</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 1: Load your data ===</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'data/CLV.csv'</span>)  <span class="co"># &lt;-- Your file path looks good</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 2: Map loyalty status to ordered numeric values ===</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>loyalty_order <span class="op">=</span> [<span class="st">'Aurora'</span>, <span class="st">'Nova'</span>, <span class="st">'Star'</span>]</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>loyalty_map <span class="op">=</span> {level: i <span class="cf">for</span> i, level <span class="kw">in</span> <span class="bu">enumerate</span>(loyalty_order)}</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'loyalty_numeric'</span>] <span class="op">=</span> df[<span class="st">'Loyalty Card'</span>].<span class="bu">map</span>(loyalty_map)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 3: Drop rows with missing values in key columns ===</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'loyalty_numeric'</span>, <span class="st">'Salary'</span>, <span class="st">'Enrollment Type'</span>, <span class="st">'CLV'</span>])</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 4: Create dummy variables for enrollment type ===</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.get_dummies(df, columns<span class="op">=</span>[<span class="st">'Enrollment Type'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 5: Define your predictors ===</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>predictors <span class="op">=</span> [<span class="st">'loyalty_numeric'</span>, <span class="st">'Salary'</span>] <span class="op">+</span> [col <span class="cf">for</span> col <span class="kw">in</span> df.columns <span class="cf">if</span> col.startswith(<span class="st">'Enrollment Type_'</span>)]</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[predictors]</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'CLV'</span>]</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 6: Fit the linear regression model ===</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>model.fit(X, y)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="co"># === STEP 7: Print results ===</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Intercept: </span><span class="sc">{</span>model<span class="sc">.</span>intercept_<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, coef <span class="kw">in</span> <span class="bu">zip</span>(X.columns, model.coef_):</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Slope for </span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>coef<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Results</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Intercept: 10652.88</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for loyalty_numeric: -1796.82</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for Salary: -0.00</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope for Enrollment Type_Standard: -12.88</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Intercept (10652.88):</strong> This is the baseline prediction for the Customer Lifetime Value (CLV). It’s what you’d expect if someone has the lowest loyalty status (Aurora), a salary of 0, and the reference type of enrollment (which is “Standard”).</p>
<p><strong>Loyalty Status (Slope: -1796.82):</strong> This is a surprising finding! As loyalty status increases (from Aurora to Nova, or Nova to Star), CLV actually goes down by about $1,797. So, instead of CLV going up with loyalty, it’s going down.</p>
<p><strong>Salary (Slope: -0.00):</strong> There’s virtually no effect of salary on CLV. It’s so small that we can pretty much ignore it in this case.</p>
<p><strong>Enrollment Type (Slope: -12.88):</strong> If someone is enrolled through the “2018 Promotion” instead of the reference enrollment type (“Standard”), their CLV goes down by about $13. This effect is very small compared to the big impact of loyalty status.</p>
<p><em>Reasoning:</em></p>
<p>Negative loyalty slope: Maybe higher loyalty levels are associated with more discounts / more free stuff, so total CLV (profitability) actually drops?</p>
<p>Or it could just mean loyalty upgrades are happening after a decline in spending, not before.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The results of the linear regression analysis suggest a counterintuitive relationship between loyalty status and Customer Lifetime Value (CLV). Specifically, as loyalty status increases (from Aurora to Nova or Star), CLV decreases by approximately $1,797. This could be due to several factors, such as higher loyalty levels being linked to more discounts or free offerings, which lower profitability. Alternatively, this negative relationship might reflect the fact that customers may upgrade their loyalty status after experiencing a decline in spending, rather than as a result of increased spending.</p>
<p>In contrast, salary has almost no effect on CLV, which implies that salary isn’t a significant predictor in this case. Additionally, the enrollment type also shows a minimal impact on CLV, with the “2018 Promotion” enrollment resulting in a slight decrease of about $13 in CLV compared to the reference type.</p>
<p>These findings highlight the importance of understanding the dynamics between loyalty status and customer behavior, suggesting that loyalty programs might not always drive the expected increases in profitability. Further research and analysis, potentially incorporating a more complex model or exploring other influencing factors, could offer more insights into these surprising results.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>