---
title: "Causal Inference Project"
format: gfm
---

## Description

My Causal Inference project idea is to study if participation in an airline loyalty program (ex: frequent flyer) causally increases passenger retention. Basically, I want to see if the passenger who sign up stay longer than those who don't and also see if it is causally linked. I need to look up some data, but I think BTS, Kaggle, and OpenFlights might be a good place to start. Let me know your feedback!

## Project Organization

- `/code` Scripts with prefixes (e.g., `01_import-data.py`, `02_clean-data.py`) and functions in `/code/src`.
- `/data` Simulated and real data, the latter not pushed.
- `/figures` PNG images and plots.
- `/output` Output from model runs, not pushed.
- `/presentations` Presentation slides.
- `/private` A catch-all folder for miscellaneous files, not pushed.
- `/writing` Reports, posts, and case studies.
- `/.venv` Hidden project library, not pushed.
- `.gitignore` Hidden Git instructions file.
- `.python-version` Hidden Python version for the reproducible environment.
- `requirements.txt` Information on the reproducible environment.

## Reproducible Environment

After cloning this repository, go to the project's terminal in Positron and run `python -m venv .venv` to create the `/.venv` project library, followed by `pip install -r requirements.txt` to install the specified library versions.

Whenever you install new libraries or decide to update the versions of libraries you use, run `pip freeze > requirements.txt` to update `requirements.txt`.

For more details on using GitHub, Quarto, etc. see [ASC Training](https://github.com/marcdotson/asc-training).
